# Generated by Django 2.2.6 on 2019-10-29 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='telephone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Контактный номер'),
        ),
        migrations.AlterField(
            model_name='primary',
            name='back_shape',
            field=models.CharField(blank=True, choices=[('Нормальная', 'Нормальная'), ('Плоская', 'Плоская'), ('Плоско-выгнутая', 'Плоско-выгнутая'), ('Сутуловатость', 'Сутуловатость'), ('Круглая', 'Круглая'), ('Кругло-вогнутая', 'Кругло-вогнутая')], max_length=20, null=True, verbose_name='Форма спины'),
        ),
        migrations.AlterField(
            model_name='primary',
            name='body_type_father',
            field=models.CharField(blank=True, choices=[('Эктоморф', 'Эктоморф'), ('Эндоморф', 'Эндоморф'), ('Мезоморф', 'Мезоморф')], max_length=10, null=True, verbose_name='Тип тела отца'),
        ),
        migrations.AlterField(
            model_name='primary',
            name='body_type_mather',
            field=models.CharField(blank=True, choices=[('Эктоморф', 'Эктоморф'), ('Эндоморф', 'Эндоморф'), ('Мезоморф', 'Мезоморф')], max_length=10, null=True, verbose_name='Тип тела матери'),
        ),
        migrations.AlterField(
            model_name='primary',
            name='chest_shape',
            field=models.CharField(blank=True, choices=[('Уплощенная', 'Уплощенная'), ('Цилиндрическая', 'Цилиндрическая'), ('Коническая', 'Коническая'), ('Нормальная', 'Нормальная')], max_length=15, null=True, verbose_name='Форма грудной клетки'),
        ),
        migrations.AlterField(
            model_name='primary',
            name='concept',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Концепт(техническая гребля)'),
        ),
        migrations.AlterField(
            model_name='primary',
            name='concept_500',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Концепт 500м'),
        ),
        migrations.AlterField(
            model_name='primary',
            name='height_father',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Рост отца'),
        ),
        migrations.AlterField(
            model_name='primary',
            name='height_mather',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Рост матери'),
        ),
        migrations.AlterField(
            model_name='primary',
            name='jump_place',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Прыжок в длину с места'),
        ),
        migrations.AlterField(
            model_name='primary',
            name='motivation',
            field=models.CharField(blank=True, choices=[('Низкая', 'Низкая'), ('Средняя', 'Средняя'), ('Высокая', 'Высокая')], max_length=15, null=True, verbose_name='Мотивация к тренеровочному процессу'),
        ),
        migrations.AlterField(
            model_name='primary',
            name='nervous_system_potential',
            field=models.CharField(choices=[('Слабая', 'Слабая'), ('Средне-слабая', 'Средне-слабая'), ('Средняя', 'Средняя'), ('Средне-сильная', 'Средне-сильная'), ('Сильная', 'Сильная')], default='Средняя', max_length=15, verbose_name='Потенциал нервной системы'),
        ),
        migrations.AlterField(
            model_name='primary',
            name='past_diseases',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Перенесенные заболевания(травмы)'),
        ),
        migrations.AlterField(
            model_name='primary',
            name='pull_ups',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Подтягивания на перекладине'),
        ),
        migrations.AlterField(
            model_name='primary',
            name='recommendations',
            field=models.ManyToManyField(blank=True, null=True, to='registry.Sport_type', verbose_name='Рекомендации'),
        ),
        migrations.AlterField(
            model_name='primary',
            name='run_1500',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Бег 1500м'),
        ),
        migrations.AlterField(
            model_name='primary',
            name='run_30',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Бег 30м'),
        ),
        migrations.AlterField(
            model_name='primary',
            name='weight_father',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Вес отца'),
        ),
        migrations.AlterField(
            model_name='primary',
            name='weight_mather',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Вес матери'),
        ),
        migrations.AlterField(
            model_name='primary',
            name='willed_qualities',
            field=models.CharField(blank=True, choices=[('Не развитый', 'Не развитый'), ('Низкий', 'Низкий'), ('Высокий', 'Высокий')], max_length=15, null=True, verbose_name='Развитие волевых качеств'),
        ),
        migrations.AlterField(
            model_name='sportsman',
            name='location',
            field=models.TextField(blank=True, null=True, verbose_name='Место жительства'),
        ),
        migrations.AlterField(
            model_name='sportsman',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='sportsman',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.Parent', verbose_name='Представитель'),
        ),
        migrations.AlterField(
            model_name='sportsman',
            name='patronymic',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='sportsman',
            name='school_progress',
            field=models.CharField(blank=True, choices=[('Отл.', 'Отл.'), ('Хор.', 'Хор.'), ('Удов', 'Удов')], max_length=4, null=True, verbose_name='Успеваемость в школе'),
        ),
        migrations.AlterField(
            model_name='sportsman',
            name='sports_facility',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Спортивное учреждение'),
        ),
        migrations.AlterField(
            model_name='sportsman',
            name='surname',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='sportsman',
            name='telephone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Контактный номер'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='arm_span',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Размах рук(см)'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='arterial_pressure_f',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Артериальное давление(верхнее число)'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='arterial_pressure_s',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Артериальное давление(нижнее число)'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='breath_hold_stange',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Проба с задер.дых.на вдохе(проба Штанге)сек'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='chest_girth_inspiration',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Обхват грудной клетки на вдохе(см)'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='chss',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='PWC ЧСС'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='close_eyes',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Закрытые глаза'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='date',
            field=models.DateField(verbose_name='Дата обследования'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='deadweight_dynamometry',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Становая динамометрия'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='dynamometry_left',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Динамометрия левой кисти(кг)'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='dynamometry_right',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Динамометрия правой кисти(кг)'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='excursion_difference',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Экскурсия(разница)'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='exhaling_chest',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Обхват грудной клетки на выдохе(см)'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='kg',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='PWC Кг мм'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Длина тела(см)'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='mpc',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='МПК мл/мин/кг'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='muscle_mass',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='% мышечной массы'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='open_eyes',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Открытые глаза (фон)'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='spirometry_yellow',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Спирометрия(ЖЕЛ)мл'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='spit_leg_length',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Длина ног от вертела(см)'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='tallow_mass',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='% жировой массы'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='target',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Мишень'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='torso_length_7',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Длина туловища от 7-го шейного позвонка(см)'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Вес тела (кг)'),
        ),
        migrations.AlterField(
            model_name='umo',
            name='adaptive_capabilities',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Адаптационные возм.организма'),
        ),
        migrations.AlterField(
            model_name='umo',
            name='cns_functional',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Фукц.возможности ЦНС'),
        ),
        migrations.AlterField(
            model_name='umo',
            name='cns_level',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Уров.работоспособности ЦНС'),
        ),
        migrations.AlterField(
            model_name='umo',
            name='functional_reserves',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Функциональные резервы'),
        ),
        migrations.AlterField(
            model_name='umo',
            name='golden_ratio',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Золотое сечение(0,16-0,62)'),
        ),
        migrations.AlterField(
            model_name='umo',
            name='grv',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='ГРВ'),
        ),
        migrations.AlterField(
            model_name='umo',
            name='integral_indicator',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Интегральный показатель'),
        ),
        migrations.AlterField(
            model_name='umo',
            name='load',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ЭКГ с нагрузкой'),
        ),
        migrations.AlterField(
            model_name='umo',
            name='plantometry',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Плантометрия'),
        ),
        migrations.AlterField(
            model_name='umo',
            name='rest',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ЭКГ в покое'),
        ),
        migrations.AlterField(
            model_name='umo',
            name='spectral_analysis',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Спектральный анализ'),
        ),
        migrations.AlterField(
            model_name='umo',
            name='voltage_index',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Индекс напряжения'),
        ),
    ]
