# Generated by Django 2.2.6 on 2019-10-28 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Primary',
            fields=[
                ('survey_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registry.Survey')),
                ('date_of_test', models.DateField(auto_now_add=True, verbose_name='Дата прохождения тестирования')),
                ('place_of_birth', models.TextField(verbose_name='Место рождения')),
                ('place_of_study', models.CharField(max_length=300, verbose_name='Место обучения')),
                ('school_progress', models.CharField(choices=[('Отл.', 'Отл.'), ('Хор.', 'Хор.'), ('Удов', 'Удов')], max_length=4, verbose_name='Успеваемость в школе')),
                ('sports_facility', models.CharField(max_length=250, verbose_name='Спортивное учреждение')),
                ('past_diseases', models.CharField(max_length=250, verbose_name='Перенесенные заболевания(травмы)')),
                ('height_father', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Рост отца')),
                ('weight_father', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Вес отца')),
                ('body_type_father', models.CharField(choices=[('Эктоморф', 'Эктоморф'), ('Эндоморф', 'Эндоморф'), ('Мезоморф', 'Мезоморф')], max_length=10, verbose_name='Тип тела отца')),
                ('height_mather', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Рост матери')),
                ('weight_mather', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Вес матери')),
                ('body_type_mather', models.CharField(choices=[('Эктоморф', 'Эктоморф'), ('Эндоморф', 'Эндоморф'), ('Мезоморф', 'Мезоморф')], max_length=10, verbose_name='Тип тела матери')),
                ('chest_shape', models.CharField(choices=[('Уплощенная', 'Уплощенная'), ('Цилиндрическая', 'Цилиндрическая'), ('Коническая', 'Коническая'), ('Нормальная', 'Нормальная')], max_length=15, verbose_name='Форма грудной клетки')),
                ('back_shape', models.CharField(choices=[('Нормальная', 'Нормальная'), ('Плоская', 'Плоская'), ('Плоско-выгнутая', 'Плоско-выгнутая'), ('Сутуловатость', 'Сутуловатость'), ('Круглая', 'Круглая'), ('Кругло-вогнутая', 'Кругло-вогнутая')], max_length=20, verbose_name='Форма спины')),
                ('speed', models.PositiveIntegerField(verbose_name='Скорость%')),
                ('strength', models.PositiveIntegerField(verbose_name='Сила%')),
                ('stamina', models.PositiveIntegerField(verbose_name='Выносливость%')),
                ('coordination', models.PositiveIntegerField(verbose_name='Координация%')),
                ('nervous_system_potential', models.CharField(choices=[('Слабая', 'Слабая'), ('Средне-слабая', 'Средне-слабая'), ('Средняя', 'Средняя'), ('Средне-сильная', 'Средне-сильная'), ('Сильная', 'Сильная')], max_length=15, verbose_name='Потенциал нервной системы')),
                ('run_30', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Бег 30м')),
                ('jump_place', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Прыжок в длину с места')),
                ('pull_ups', models.PositiveIntegerField(verbose_name='Подтягивания на перекладине')),
                ('concept', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Концепт(техническая гребля)')),
                ('run_1500', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Бег 1500м')),
                ('concept_500', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Концепт 500м')),
                ('motivation', models.CharField(choices=[('Низкая', 'Низкая'), ('Средняя', 'Средняя'), ('Высокая', 'Высокая')], max_length=15, verbose_name='Мотивация к тренеровочному процессу')),
                ('willed_qualities', models.CharField(choices=[('Не развитый', 'Не развитый'), ('Низкий', 'Низкий'), ('Высокий', 'Высокий')], max_length=15, verbose_name='Развитие волевых качеств')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.Coach', verbose_name='Тренер')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.Parent', verbose_name='Представитель')),
                ('recommendations', models.ManyToManyField(to='registry.Sport_type', verbose_name='Рекомендации')),
            ],
            options={
                'verbose_name': 'ПДК',
                'verbose_name_plural': 'ПДК',
                'ordering': ('date_of_test',),
            },
            bases=('registry.survey',),
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование разряда')),
                ('rank', models.PositiveIntegerField(verbose_name='Разряд')),
            ],
            options={
                'verbose_name': 'Разряд',
                'verbose_name_plural': 'Разряд',
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='pdk',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='pdk',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='pdk',
            name='physique_of_father',
        ),
        migrations.RemoveField(
            model_name='pdk',
            name='physique_of_mother',
        ),
        migrations.RemoveField(
            model_name='pdk',
            name='previous_sport',
        ),
        migrations.RemoveField(
            model_name='pdk',
            name='recommendations',
        ),
        migrations.RemoveField(
            model_name='pdk',
            name='sportsman_pdk',
        ),
        migrations.RemoveField(
            model_name='pdk',
            name='survey_ptr',
        ),
        migrations.AddField(
            model_name='survey',
            name='foot_length',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Длина стопы (см)'),
        ),
        migrations.AddField(
            model_name='umo',
            name='ultrasound_heart',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Узи сердца'),
        ),
        migrations.AlterField(
            model_name='sportsman',
            name='date_of_birth',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='sportsman',
            name='sport_desire',
            field=models.BooleanField(blank=True, verbose_name='Желание заниматься спортом'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='arterial_pressure_f',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Артериальное давление(верхнее число)'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='arterial_pressure_s',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Артериальное давление(нижнее число)'),
        ),
        migrations.DeleteModel(
            name='Functional_potential',
        ),
        migrations.DeleteModel(
            name='PDK',
        ),
        migrations.DeleteModel(
            name='Physique',
        ),
        migrations.DeleteModel(
            name='Previous_sport',
        ),
        migrations.AddField(
            model_name='primary',
            name='sportsman_pdk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.Sportsman', verbose_name='Участник тестир.'),
        ),
        migrations.AddField(
            model_name='sportsman',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.Rank', verbose_name='Разряд'),
        ),
    ]
