# Generated by Django 2.2.6 on 2019-10-29 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_auto_20191029_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsman',
            name='rank',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='registry.Rank', verbose_name='Разряд'),
            preserve_default=False,
        ),
    ]
