# Generated by Django 2.2.6 on 2019-10-29 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_auto_20191029_2257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rank',
            options={'ordering': ('name', 'rank'), 'verbose_name': 'Разряд', 'verbose_name_plural': 'Разряд'},
        ),
        migrations.AlterField(
            model_name='sportsman',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.Rank', verbose_name='Разряд'),
        ),
    ]
