# Generated by Django 2.2.6 on 2019-10-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_auto_20191029_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primary',
            name='date_of_test',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата прохождения тестирования'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата обследования'),
        ),
        migrations.AlterField(
            model_name='umo',
            name='date_of_pass',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата прохождения УМО'),
        ),
    ]
