# Generated by Django 2.2.6 on 2019-10-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_auto_20191029_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primary',
            name='recommendations',
            field=models.ManyToManyField(blank=True, to='registry.Sport_type', verbose_name='Рекомендации'),
        ),
    ]
