# Generated by Django 2.2.6 on 2019-10-30 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_auto_20191029_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primary',
            name='date_of_test',
            field=models.DateField(blank=True, null=True, verbose_name='Дата прохождения тестирования'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='sportsman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.Sportsman', verbose_name='Спортсмен'),
        ),
        migrations.AlterField(
            model_name='umo',
            name='date_of_pass',
            field=models.DateField(blank=True, null=True, verbose_name='Дата прохождения УМО'),
        ),
    ]
