# Generated by Django 2.2.6 on 2019-11-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0008_survey_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primary',
            name='coordination',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Координация%'),
        ),
        migrations.AlterField(
            model_name='primary',
            name='nervous_system_potential',
            field=models.CharField(blank=True, choices=[('Слабая', 'Слабая'), ('Средне-слабая', 'Средне-слабая'), ('Средняя', 'Средняя'), ('Средне-сильная', 'Средне-сильная'), ('Сильная', 'Сильная')], default='Средняя', max_length=15, null=True, verbose_name='Потенциал нервной системы'),
        ),
        migrations.AlterField(
            model_name='primary',
            name='recommendations',
            field=models.ManyToManyField(blank=True, null=True, to='registry.Sport_type', verbose_name='Рекомендации'),
        ),
        migrations.AlterField(
            model_name='primary',
            name='speed',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Быстрота'),
        ),
        migrations.AlterField(
            model_name='primary',
            name='stamina',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Выносливость%'),
        ),
        migrations.AlterField(
            model_name='primary',
            name='strength',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Сила%'),
        ),
        migrations.AlterField(
            model_name='sportsman',
            name='gender',
            field=models.CharField(blank=True, choices=[('М', 'М'), ('Ж', 'Ж')], max_length=10, null=True, verbose_name='Пол'),
        ),
    ]
