# Generated by Django 2.2.6 on 2019-11-12 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0010_auto_20191112_0144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='primary',
            options={'ordering': ('date',), 'verbose_name': 'Первичное', 'verbose_name_plural': 'Первичные'},
        ),
        migrations.AlterModelOptions(
            name='umo',
            options={'ordering': ('date',), 'verbose_name': 'УМО', 'verbose_name_plural': 'УМО'},
        ),
        migrations.RemoveField(
            model_name='primary',
            name='date_of_test',
        ),
        migrations.RemoveField(
            model_name='umo',
            name='date_of_pass',
        ),
    ]
